name: BasicUploadUbuntu

on:
  push:
    branches: [ "master", "main" ]

jobs:

  deployment:
    runs-on: ubuntu-latest 
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Register To Catalog
      env:
        DATAMINER_TOKEN: ${{ secrets.DATAMINER_TOKEN }}
      run: |
        dotnet publish `
          -p:Version="0.0.${{ github.run_number }}-prerelease" `
          -p:VersionComment="This is just a pre-release version." `
          -p:CatalogPublishKeyName="DATAMINER_TOKEN" `
          -p:CatalogDefaultDownloadKeyName="DATAMINER_TOKEN" `
